### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by UmutKDev** [jikan-me/jikan-rest#234]
`[GET] /
23:03:28:19
2022-06-05T20:03:32.828Z    963bea72-5297-419c-9af6-7a3845aa9b9e    ERROR    Unhandled Promise Rejection     {"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: ENOENT: no such file or directory, mkdir '/var/task/node_modules/jikan4.js/.Jikan/cache/anime'","reason":{"errorType":"Error","errorMessage":"ENOENT: no such file or directory, mkdir '/var/task/node_modules/jikan4.js/.Jikan/cache/anime'","code":"ENOENT","errno":-2,"syscall":"mkdir","path":"/var/task/node_modules/jikan4.js/.Jikan/cache/anime","stack":["Error: ENOENT: no such file or directory, mkdir '/var/task/node_modules/jikan4.js/.Jikan/cache/anime'","    at mkdirSync (node:fs:1349:3)","    at CacheManager.set (/var/task/node_modules/jikan4.js/dist/core/cache.js:63:36)","    at APIClient.<anonymous> (/var/task/node_modules/jikan4.js/dist/core/api.js:204:81)","    at Generator.next (<anonymous>)","    at fulfilled (/var/task/node_modules/tslib/tslib.js:112:62)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: ENOENT: no such file or directory, mkdir '/var/task/node_modules/jikan4.js/.Jikan/cache/anime'","    at process.<anonymous> (file:///var/runtime/index.mjs:775:15)","    at process.emit (node:events:539:35)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
Unknown application error occurred`

I get this on vercel

**Comment by irfan-dahir** [comment]
This is not a REST API issue.
Please refer to the appropriate repo: https://github.com/rizzzigit/jikan4.js
